version: '3.5'
services:
  mysql-order:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-order-service:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

  mysql-user:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-user-service:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

  user-service:
    build:
      context: grpc
      dockerfile: user-service.dockerfile
    image: user-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=doc
    depends_on:
      - mysql-user
    deploy:
      replicas: 1

  order-service:
    build:
      context: grpc
      dockerfile: order-service.dockerfile
    image: order-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=doc
    depends_on:
      - mysql-order
      - user-service
    deploy:
      replicas: 1

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - order-service
    ports:
      - "4000:4000"

networks:
  default:
    driver: bridge
    name: ordersystem

volumes:
  mysql-order-service:
  mysql-user-service:
